version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: ./backend
    container_name: celery_worker
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./backend:/code
    environment:
      # Note: We use 'redis' as the hostname because services can
      # communicate using their service names inside the Docker network.
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis